language: node_js

node_js:
  - "5.3"

before_install:
  - npm install -g ember-cli bower

install:
  - "node --version"
  - "npm --version"
  - "git --version"
  - "npm install"
  - "bower install"

before_script:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"

after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

env:
  global:
    - TRAVIS_CI=true
