language: node_js
sudo: false

node_js:
  - '5.3'

branches:
  except:
    - /^v[0-9\.]+/

before_install:
  - npm install -g coveralls pr-bumper
  - pr-bumper check

after_success:
  - sed -i -- 's/SF:ember-frost-button\/\(.*\)/SF:addon\/\1.js/' coverage/lcov.info && rm -f coverage/lcov.info--
  - cat coverage/lcov.info | coveralls

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  matrix:
    - CXX=g++-4.8
  global:
    - secure: COlOrjIlMucNZ3qDMPM6cGZ7H1WU93L9c5NclJzXP1IeUYncYkDis0+G+j7Rv7IPHwY53Z7Ms9ghRCk7rk1mM9jEAZZkJV6vfsgTYsHLusym9a4JckvXiAo3sxbZvHkcsU0yrmsc1l5p68RvvJ4DmlH0WdQGvtr4o8RpDbk76ZEnht3cvq5ANGZho7OUskAcNYdFc5r1nuH7I19zYO/cJrdQO9DU9I4x2AuAoBbC96qwVdn444s+hUb07urfL1ITh6+wCnxROkDlIrXxXucSSHJ1ML7HxvPsRkuUxvJI+HjPovk/PhnNreA6i8vGJRhZuDE+/+GTyVCW82Tmpx08A451T/FLBDMRdknBA7Y2U3bCQAv57rvn3giFXrYhKAtvO7ZlWL3/vWC1YQcRARVHfdCZRjUkVxnWMAdHb2mfZ+RhRVR1lcEXFF4CtNcz+1hnfDG1L5sCeJbP2WAHAhGuRYs470tdH7dA15xKOCTszNP0r7zhtwq9fbu1Or86suZgOihuT350OXvDQlh+Yli1Pbysvx9S/VXJfu0AykbQIKUgBWnlTJGPe/s1lMNX/34hZZIbzv8RY2jvEeVcCJ0cdmlrT3Sa+6CChkw982vsdKju9JcYim5UjZk84ExvVtkSaYu6UjM4BkFv/hFAiIX0g4fFcYeIL4mfVq/KwNsIE28=

before_deploy:
  - pr-bumper bump

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: B4UIGF/KLwS3vOpemKDRLtDjtl8rl4bpYClQEcjzAALx23nieKFCKXEKbOM5W7U8XNx0ygWuYNcaTnuKP6G67ijCdZRP7SnRPc5hP+F0Hhv35i2VGcUaczqCJpkuaC/8ncjoR9asBTFyNzVlUag5/ZdmCzFBvn+PUpSMUBsUNxAhulDXUsuG8XeCOEAt8Bz1Ej4oN4DP8dDJZQs+vCgZl6156YDHk9ZHWyGdwMmA2CI7YFq6iy5Kc+QvTu25Ymjbz5HeIY8c6fTqYbpvYMm1zBLWFFRmrv93O87YCv61Lw7F+GbxZw6KYn1ufL7puGQ+ffgiXqZR8OZfm6DMHHIGl//wE5OJ6qbxLos/GFAakUCKdGtF6OEjKM/0tW6OD98i0FBiAxXYF9mSy8yC2npFKBDkvW2ghsOZTFuyIcfCnbp4iahJWXaKNpStdPIeFxq52fcjMx1cE4+XOdjwQ1hx/FeVpJrgNn/zVGzqTmzXmrWzMZ9T3ANB8xT6JpAHzP+adap3GUu5kBwRYjWyvVvz0Mh8xF5s2efam9z6MI1Blt+uRqt9wEZTa/8Im44IDXLKyYPBU9R81RFTkiDQLzTp0Ww7DMjeqmFU4M8JkjgVfDsKtIJafvnrIPGxDrNgq5TlC73Up46FS/lAzPTkIf/PgnD8chrtc44gHJtm2rnmrEw=
  on:
    branch: master
    tags: false

notifications:
  slack:
    secure: bEDzMCHgmL/mYj7e8wBhmVAbj6mhYceDwaF6iG8iTGMN0yzvAmBdyzkvqOYIrPjcVikT7Vs5zdSFxDYyh/6KP/5bE/aezQDIMtEgZDArgZ5mc7DOJl5w9XyL5id/K4MLYXpLEnv6Ws1hBSt56OhRwO39Rnwy50nL+rpKcvEx6vbnJKD9I8rQTR6G8sEZ5sCFLi3oF5vpmFRgWq17OuE9sBODF/Q7IA/mnpvcYHJHqz5i+2I/IeZ6yxUv3d+iUNdY3qR6Etd4qympDnDg1PndvuCnniBn+cf1wnd04AgU1pUFesE7jtY1feM/qxRqKtPNNIV7x4WD1+UZQIGAnEBeoxMIb2VrRTtHfBOiXCHfQ12V0CkcgK3Ca+Q/RC44xyz06F9rDsB96x6+wZWpPu5GnZc+hXv5REMvk7c4AIhwR5sHw/kAIUzNQgjau9MKoZe5NagCmhdl7JoNFtewHW7Mpz6k2XBoDm2c98R0TOVfD/apjERKfrIhaep6mFOUV4TO0vI3ZJt0FHTo5rHWBd0MIub7ccil3uEXzS4VV0xrijhq9+0DUWBWRhB8h2DlaZCu6fCdrSBrtY0KJFi6t5ipnTQcx2Q4vq4pYHLF6tIjXATuqW8SCWuf5Ma8DvW/fAtw02c6N27wqxG83O82RejnAJzzTZAeleoxHA+ei2/r5CM=
