language: node_js

sudo: false

node_js:
  - 5.3

before_install:
  - npm install -g ember-cli bower phantomjs

install:
  - npm install
  - bower install

before_script:
  - export DISPLAY=99:0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then npm run-script check-version-bump; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then echo "Skipping check-version-bump"; fi
  - npm test

after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then npm run-script frost-publish; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then echo "Skipping frost-publish"; fi

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  firefox: 44.0
